### ISSUE TITLE
Audio stops after 10 minutes in background

### ISSUE THREAD

**Issue by yahoai** [DoubleSymmetry/react-native-track-player#1092]
**Describe the bug**
Audio stops after 10 minutes in background

![](https://docs-assets.developer.apple.com/published/547e36d6fd/d30003e5-09aa-46db-9cac-181511bb2113.png)
I set it up as shown in the image. But after 10 minutes the audio stops.

**Comment by AChevallier** [comment]
I have the same issue and it became more big since december.

@yahoai Do you have more informations?

**Comment by yahoai** [comment]
@AChevallier The app dies after 10 minutes for both url or local audio

Background audio playback works normally, but the problem seems to be that the app is closed.

**Comment by puckey** [comment]
@yahoai does background audio continue? and when you switch back to the app, it restarts? have you spotted anything in any logs?

**Comment by yahoai** [comment]
@puckey The app plays normally even in the background. It goes well on the next track. However, after about 10 minutes, the app is terminated.

In xcode, signal 9 log is printed.

https://github.com/react-native-kit/react-native-track-player/issues/792

It seems to be the same phenomenon as the above issue, but it does not seem to have been resolved yet.

**Comment by AChevallier** [comment]
@yahoai @puckey 
I read #792 and it's very interesting.

On our side, the problem (crash of the app, the app restarts) happen more often on older devices(iphone 6S/7/8) WHEN they are using bluetooth/airplay.
The problem has become bigger since the end of november.
<img width="956" alt="Screenshot 2021-01-27 at 15 06 34" src="https://user-images.githubusercontent.com/10862109/106002777-cf665480-60b1-11eb-9de8-08945727cca8.png">
The percentage of the people who have the problem after 6/7min of listening.

The problem became very annoying...

Some people already tried the "fix" : https://github.com/react-native-kit/react-native-track-player/issues/792#issuecomment-756171765 ?

**Comment by yahoai** [comment]
@AChevallier 

In the xcode debug session, the cpu usage is increasing, so I tried to hide the part that draws the view in the background state.

The cpu usage rises when the audio changes and then returns to 0%, and the app is not dying.

**Comment by yahoai** [comment]
@AChevallier @puckey 


After adjusting the cpu usage, The signal 9 phenomenon is not occurring.

However, in the case of playback using url in the background, the phenomenon of stopping in buffering remains even if waitForBuffer :true is set.
