### ISSUE TITLE
setRate() is not sync with notification centre's duration and current time value

### ISSUE THREAD

**Issue by krunalbad** [DoubleSymmetry/react-native-track-player#1104]
![Screenshot 2021-02-02 at 4 35 23 PM](https://user-images.githubusercontent.com/45413622/106592064-09819b80-6575-11eb-9a36-5b3be6bb121d.png)

**Comment by ccurtin** [comment]
Also noticing this when the playback rate is below a certain threshold

**Comment by ccurtin** [comment]
@krunalbad There's a number of things I've noticed.
- It appears to me that `setRate()` must be called _every_ time another operation happens on the track player: play, pause, next, skip.
- I've noticed that not only that but you must also use `pause()` then  re-trigger the rate `setRate()` and then call `play()` again in order to get the Notification Player and UI Player to sync up, otherwise the Notification Player resets its rate to `1x`. It seems to me like `pause` MUST be called to trigger the "remote/notification" state when updating the rate in the UI.
- Lastly, I've found that I had to add a `pitchAlgorithm`, otherwise the ratio of speed between the the Notification Player and UI Player were slightly different in which the lag was compounded depending on the length of the track.
- One other thing just to take note of is that `setRate` accepts floats like `.1.6` but you'll notice if you console log `getRate(1.6)` that the value isn't `1.6`, but rather `1.600000023841858`. If using state management probably best to store the value of `getRate()` rather than using a value from a variable like 1.6, but really shouldn't affect the experience either way.

**Comment by krunalbad** [comment]
Does it work for you? I have tried this but the issue is still persisting for me 😞

**Comment by ccurtin** [comment]
The setup for us looks like this:

```js
import TrackPlayer, { PITCH_ALGORITHM_VOICE } from 'react-native-track-player'

const initialSetupAudible = async (
    tracks,
    reset = false
  ) => {
    const tracksFormatted = await tracks.map(({ id, url, title, artist, artwork }) => ({
      id,
      url,
      title,
      artist,
      artwork,
      pitchAlgorithm: PITCH_ALGORITHM_VOICE
    }))
  
    if (reset) {
      await TrackPlayer.reset()
    }
    await TrackPlayer.setupPlayer().then(() => {
      TrackPlayer.updateOptions({
        // stop audio when app closes(android)
        stopWithApp: true,
        jumpInterval: 30,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
          TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
          TrackPlayer.CAPABILITY_STOP,
          TrackPlayer.CAPABILITY_JUMP_FORWARD,
          TrackPlayer.CAPABILITY_JUMP_BACKWARD
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
          TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
          TrackPlayer.CAPABILITY_SEEK_TO,
          TrackPlayer.CAPABILITY_JUMP_FORWARD,
          TrackPlayer.CAPABILITY_JUMP_BACKWARD
        ],
        notificationCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
          TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
          TrackPlayer.CAPABILITY_SEEK_TO,
          TrackPlayer.CAPABILITY_JUMP_FORWARD,
          TrackPlayer.CAPABILITY_JUMP_BACKWARD
        ]
      })
    })
    await TrackPlayer.add(tracksFormatted)
  }
  ```

**Comment by krunalbad** [comment]
This is what I did exactly.  @ccurtin 
Anyway, can you share the RN version and RNTP version as well if possible?

**Comment by mitchdowney** [comment]
@dcvz has this issue been resolved in v2? We had the same issue @ccurtin reported, and to workaround it we started calling pause before remote-play on iOS only...but we're also having problems where remote play/pause toggle has to be pressed twice sometimes to work as intended, and I think the remote-play -> pause -> play hack might be why. I'm going to try removing the workaround, but I'm worried the setRate problems will resume if I do that.

**Comment by dcvz** [comment]
Hi @mitchdowney ! At some point we did a cleanup of issues to try to take it more manageable to maintain the repository. I’m not sure about this specific issue and whether it’s still an issue in v2.

We’d love if you could give this a try and let us know. Otherwise, we’ll add it to the backlog to check on after our current efforts on Android
