### ISSUE TITLE
Seekbar

### ISSUE THREAD

**Issue by rutul089** [DoubleSymmetry/react-native-track-player#1128]
Seekbar not updating with the duration and progress with ProgressComponent

**Comment by jakecronin** [comment]
I am also having this problem. ProgressComponent state does not seem to be updated by the track player. Audio playback is working just fine, but neither state.duration nor state.position are updating.

Does anything need to be done to connect the ProgressComponent to the TrackPlayer? The documentation is limited on this subject.

**Comment by curiousdustin** [comment]
Can you show how you are extending `ProgressComponent`? 

https://react-native-track-player.js.org/getting-started/#progress-component

**Comment by jakecronin** [comment]
I ended up getting things working (see #641). The problem seems to be that ProgressComponent relies on ComponentDidMount, which I was overriding in my ProgressComponent implementation.

My solution was adding `super.componentDidMount?.apply(this);` at the top of my `componentDidMount` function. Same thing for `componentWillUnmount`.

**Comment by curiousdustin** [comment]
@rutul089 , do you happen to have a similar issue, where you have overridden `componentDidMount`?
