### ISSUE TITLE
After upgrading to V2.0.3, i am getting this error TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by mohity777** [DoubleSymmetry/react-native-track-player#1247]
**Describe the bug**

**To Reproduce**

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?

**Code**
Please, share the code that is causing the issue

**Comment by dcvz** [comment]
His @mohity777 what version did you upgrade from?
This sounds like an issue that comes up during a migration, likely an import is wrong.

Instead of `import { STATE_PLAYING }` you want to do `import { State } ` then use `Event.Playing`
this is true also for capabilities, Events, etc.. likely you missed migrating an import.

**Comment by mohity777** [comment]
Then use Event.Playing or State.Playing ?

**Comment by dcvz** [comment]
Sorry yes. `State.Playing`.
You can take a look at the example app for reference as well :)

**Comment by mohity777** [comment]
Yeah i actually did follow changes that were mentioned in the readme before opening this issue like changing imports for STATE_XXX and CAPABILITY_XXX . I will recheck if i missed somewhere and let u know.

**Comment by mohity777** [comment]
I think it was because I was using import {ProgressComponent} from 'react-native-track-player'; and using it in my code.
