### ISSUE TITLE
Resume playing after interrupting is done

### ISSUE THREAD

**Issue by marksturm** [DoubleSymmetry/react-native-track-player#1337]
Hi,
i currently "develop" currently a app for a friends webradio and notice that the player stops if a other musicsource (like youtube, or any other app with sound) starts to play. So far so good, i changed the service.js from the example and the remote duck is not closing anymore, and player paused instead of stopping.

`TrackPlayer.addEventListener(Event.RemoteDuck, async e => {
    console.log(e);
    if (e.permanent === true) {  
      //TrackPlayer.stop();
      TrackPlayer.pause();
    } else {`

But now i want to start my app to play again, after the other app (like youtube, or any other app with sound) is done interrupting my music stream.

Any suggestions?

**Comment by bradleyflood** [comment]
Hi Mark. I believe this isn't possible because your app would have no way of telling when apps like YouTube is finished.

The Remote Duck event is for "temporary" sound events, like a phone call or other interruption where the user would want the playback to resume afterwards. But if the user switches apps entirely (for example to YouTube) then this is not handled by the remote duck event, and the user has chosen to listen to something else.

**Comment by marksturm** [comment]
Hey, thanks for your response.

I tried some other Radio Apps, they are somehow able to resume playing music, after an other app is done with playing sounds.

I tried also simple to lower the volume to 0 - but i dont find a way to get a response from the remote duck after a other app is done playing sounds, cause other apps run into permanat===true ...

**Comment by bradleyflood** [comment]
Ok thanks. I'll close this for now then.
