### ISSUE TITLE
RTNP & AirPlay is kind-of broken @ iOS 15.4

### ISSUE THREAD

**Issue by DennisdeWitNL** [doublesymmetry/react-native-track-player#1408]
Hello,

It seems react-native-track-player is broken with iOS 15.4. I am running the beta, but discovered there is no sound when switching from iPhone to my HomePod Mini. The HomePod is showing a white glow and knows there is connection. There is just no audio streaming through. 

Version: RTNP 2.1.2

How to reproduce:

- Open your app with RNTP;
- Play the stream;
- Press the power button and choose AirPlay. Choose for your HomePod Mini
- The HomePod Mini is now connected, there is just no audio going through it.

On the other side, there is some kind of work-around.
- Open your app with RNTP;
- Go to VLC and run your stream, press AirPlay and click your HomePod Mini;
- Stop playing in VLC but keep AirPlay active;
- Press the play button in your RTNP app.

Also, when I clicked the video module in my app, sound started playing on my HomePod Mini. When I then click the play button of RNTP, ta-daaaa, the audio is running.

Also, I noticed when switching between iPhone and HomePod Mini, the stream is stopped and will not start playing again, until I open the app and press the play button. I also have tested it on iOS 15.3, and it worked flawless. I tested it with some other apps. One app is using RNTP too and shows the same problem (not developed by me). Some other apps that certainly do not use the module, are working fine. This is why I think it must be React Native Track Player causing the issue.

Maybe someone of the team could try to reproduce it? I am running the latest iOS and HomePod Mini beta. Any help would be appreciated.

Thank you.

**Comment by DennisdeWitNL** [comment]
This issue seems to be related to longformAudio being broken since iOS 15.4. Maybe you could take a look, @curiousdustin? :)

**Comment by acorkin** [comment]
I’m also seeing this. I hoped the RC version of 15.4 would resolve but it hasn’t. I’m able to replicate when invoking AirPlay from an iPhone 12 Pro Max, iOS 15.4 RC to:

- Apple TV HD - 15.4 RC
- Apple TV HD - 15.3.1
- M1 MacBook Air - 12.2
- Sonos Play One

The iPhone shows the connection is established and the media is playing however the Apple TV/Mac shows nothing in ‘Now Playing’.

**Comment by DennisdeWitNL** [comment]
Yes. I have exactly the same issue. And it really is an RNTP problem. VLC works fine, for example. Tested it against an Apple TV, HomePod Mini and MacBook Pro M1 Max. All with the latest software.

**Comment by martinmidtsund** [comment]
I have tested with iOS 15.4 on iPhone 12 Pro and RNTP 2.1.2 on Sonos One and Sonos Move and I’m not able to replicate this, everything is currently working fine. I have switched between different One’s, the Move and combined them without issues. I’ll come back if we experience any issues down the road.

**Comment by shashankkushwah** [comment]
Hi @martinmidtsund, The issue is still there, it's mainly with the radio stations rather than direct audio URLs. I have created a test app (attached) if you'd like to have a play around, below is the screenshot for it. 

![IMG_8788](https://user-images.githubusercontent.com/149235/161036840-543599c7-0b2c-4709-b5c6-effe6fbb8c9a.PNG)

I am experiencing problems with the first 5 radio stations in the screenshot, while the last two podcast episodes switch just fine between different AirPlay enabled devices.

Steps: 
1. Play a radio station (any in the top 5).
2. Press the AirPlay button to bring the AirPlay speakers/TV selector pop up.
3. Select a speaker/TV

The selected speaker/TV connects and the UI changes to playing in the selector pop up, but the audio doesn't play on the device.

There is another curious case where if you play a direct audio URL (any in the bottom 2), and then airplay to a speaker/TV, the audio starts playing. Then if you play a radio station (any in the top 5), it will play just fine. 

Steps: 
1. Play a direct audio URL (any in the bottom 2).
2. Press the AirPlay button to bring the AirPlay speakers/TV selector.
3. Select a speaker/TV (notice Audio playing through the selected speaker/TV)
4. Close the AirPlay pop up.
5. Press play any radio station (any in the top 5)

[TrackPlayerTest.zip](https://github.com/DoubleSymmetry/react-native-track-player/files/8388499/TrackPlayerTest.zip)

**Comment by DennisdeWitNL** [comment]
This has something to do with the SwiftAudioEx package, not specifically with RNTP.

**Comment by DennisdeWitNL** [comment]
This problem has been solved by Apple on iOS 15.5 beta 4.
