### ISSUE TITLE
2.2.0-rc.3 and 2.2.0-rc.4 don't receive RemotePause and RemotePlay from connected bluetooth device on Android

### ISSUE THREAD

**Issue by doughsay** [doublesymmetry/react-native-track-player#1582]
**Describe the Bug**

The background service events `RemotePlay` and `RemotePause` do not trigger on Android when using a connected bluetooth speaker or headphones.

**Steps To Reproduce**

1. Get the example app running on an Android device and have a bluetooth audio device connected.
2. Add `console.log` statements to the `RemotePlay` and `RemotePause` event handlers in the background service.
3. Press play in the example app
4. Use the notification play/pause button to confirm you see the log statements
5. Press the action button on your bluetooth audio device to play/pause and see the log statements do not appear

**Code To Reproduce**

No code example needed, the example app from the repo reproduces this behavior (as long as you add log statements to see it). I Checked out and tested both 2.2.0-rc.3 and 2.2.0-rc.4.

**Environment Info:**

```
System:
    OS: Linux 5.17 Pop!_OS 22.04 LTS
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.37 GB / 31.32 GB
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.18 - ~/.asdf/installs/nodejs/lts/.npm/bin/yarn
    npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
  npmGlobalPackages:
    *react-native*: Not Found
```

`react-native-track-player` versions `2.2.0-rc.3` and `2.2.0-rc.4`.

Real device: Pixel 6 Pro

**How I can Help**

I do not know Kotlin at all nor the Android SDK very well, so it would be a bit of a struggle for me to figure out why this is happening. I can help with testing and verifying; I'm in the discord server a lot.

**Comment by jspizziri** [comment]
@doughsay thanks for the report. Do you have an interest in taking a shot at this? I can provide guidance! As I've said to many folks I had no experience either but I just dove in and it wasn't that big of a deal. I can give you some suggestions of where to look too. We could effectively pair it with you doing the actual coding. It's a great way to learn and make the lib more stable while doing it!

**Comment by jspizziri** [comment]
@doughsay I have a theory as to the problem here.

In 2.1 The package overrode a class called `MesiaSessionCompat.Callback` in exoplayer that allows you to hook into core exoplayer events. [From that callback we fired our events](https://github.com/doublesymmetry/react-native-track-player/blob/v2.1/android/src/main/java/com/guichaguri/trackplayer/service/metadata/ButtonEvents.java#L29) .

However the rebuild connected those events directly to the _buttons_ clicks on the notification player rather than exoplayer events.

My intuition is that to fix this we need to add an additional override on the company class ([on top of what I did here](https://github.com/doublesymmetry/KotlinAudio/pull/28/files#diff-7d05808a134fc6efdaef2d0049ac5bf23ee4367c6c2601f159b4577f6bbb29bfR166)) to catch all the events.

It's possible doing this will result in two events being fired when the notification player is interacted with. If that's the case we'll need to either despise the events somehow or simply remove the ones fired by the actual button itself.

**Comment by jspizziri** [comment]
Were you able to take a look at this?

**Comment by doughsay** [comment]
@jspizziri yep, I have a fix here: https://github.com/doublesymmetry/KotlinAudio/pull/32

It works for me! 😅  No idea if this is a good fix or not...

Thanks a lot for your pointers on where to look.  In the end I had to use code from your linked PR that was actually removed due to code-review comments.  Good thing GitHub preserved enough of it in the discussion for me to figure things out. 🎉

**Comment by jspizziri** [comment]
Closing as in favor of https://github.com/doublesymmetry/react-native-track-player/issues/1657
