### ISSUE TITLE
RepeatMode is not working on Android

### ISSUE THREAD

**Issue by dmytrokruhlyi** [doublesymmetry/react-native-track-player#1669]
**Describe the Bug**
I tried to use RepeatMode but it is not working on Android (IOS works ok).

**Code To Reproduce**
`TrackPlayer.setRepeatMode(RepeatMode.Track);`

**Environment Info:**

> System:
>     OS: macOS 12.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
>     Memory: 358.63 MB / 16.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 16.15.0 - /usr/local/bin/node
>     Yarn: 1.22.10 - /usr/local/bin/yarn
>     npm: 8.5.5 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
>     Android SDK:
>       API Levels: 23, 28, 29, 30, 31
>       Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0
>       System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
>       Android NDK: 22.1.7171670
>   IDEs:
>     Android Studio: 2021.2 AI-212.5712.43.2112.8815526
>     Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.64.1 => 0.64.1 
>     react-native-macos: Not Found

      

`react-native-track-player` version is v3.0.   

The issue reproduces on apk build.

**Comment by jspizziri** [comment]
@dmytrokruhlyi I'm not saying you're wrong. But about a month ago we did _extensive_ testing on repeat modes and queue behavior. I would be shocked if it had broken since then. My guess is that you might not fully understand how repeat mode is intended to work. Please thoroughly read through this issue for more detail: https://github.com/doublesymmetry/react-native-track-player/pull/1501

There is however, one known issue with Android RepeatMode which is tracked here https://github.com/doublesymmetry/react-native-track-player/issues/1612

If you read through the docs and still think it's broken, I'll happily reopen this, but I'll first want documented steps on what is happening, and what you expect to happen.
