### ISSUE TITLE
useTrackPlayerEvents not working on android

### ISSUE THREAD

**Issue by devpolo** [doublesymmetry/react-native-track-player#1692]
**Describe the Bug**
useTrackPlayerEvents not firing any event on android.

**Code To Reproduce**
```ts
const App = () => {
  useTrackPlayerEvents([Event.PlaybackError], event => {
    console.log(event) // never fired
  })

  // play/pause track logic
}
```

**Environment Info:**
```
react-native-track-player: 3.1.0
tested on real android device
```

```
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 233.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/Desktop/Pro/meditatio/app/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**How I can Help**
Have you investigated the underlying JS or Swift/Android code causing this bug? `I didn't`

**Comment by jspizziri** [comment]
@devpolo I just tested and I can confirm that this hook is working on Android as I'd expect. One thing to note: is that the event you're subscribing to is the `PlaybackError`. It's possible you're not seeing anything because you're not getting any errors. Perhaps try with a more common event like `PlaybackTrackChanged` or something.

@puckey cc'ing you here since you referenced this issue on another. I don't see how this is an issue with state constant naming, but I'm worried I'm missing something.

**Comment by tatianavazquez** [comment]
I have the same error :(
