### ISSUE TITLE
Question: When should the `PlaybackTrackChanged` event fire?

### ISSUE THREAD

**Issue by bradleyflood** [doublesymmetry/react-native-track-player#1771]
I have a `TrackPlayer.addEventListener()` triggering for the `Event.PlaybackTrackChanged` event. But I am confused as to when this event is supposed to fire.

The [documentation](https://react-native-track-player.js.org/docs/api/events#playbacktrackchanged) says:
> Fired when a track is changed.

What does this mean "track is changed"?

My expectation (and hope) is that this event only fires when the player changes from track 1 to track 2 during normal playback or via direct controls (such as `skipToNext()`)

But what I am finding is that the `PlaybackTrackChanged` event is firing when I add stories to the queue using `TrackPlayer.add(tracks)`. And because I am using this event to detect which track is playing and display the title and artwork on the UI, it means when I add 5 stories to the queue, 5 of these events are fired, resulting in my UI flashing 5 different stories.

Should this event be firing during `.add(tracks)`?? Or is this a bug?

**Comment by bradleyflood** [comment]
To replicate...
```
TrackPlayer.addEventListener(Event.PlaybackTrackChanged, console.log);

await TrackPlayer.reset();
await TrackPlayer.add(tracks); // assuming tracks is an array of 5 valid Track objects
```
Output
```
 LOG  {"nextTrack": 0, "position": 0, "track": 0}
 LOG  {"position": 0, "track": 0}
 LOG  {"nextTrack": 0, "position": 0}
```

3x `PlaybackTrackChanged` events are fired by simply adding 5 stories to the queue. I realise that not only does this not match the number of stories I added (5), but also it's confusing because technically no tracks have "changed" I only added them to the queue. I haven't even started playing yet.

Thoughts?

**Comment by jspizziri** [comment]
@bradleyflood the log you sent mostly makes sense to me assuming there was a track in the queue initially.

```
// a track was added to the queue (looks like the repeat mode is queue or track)
LOG  #1 - {"nextTrack": 0, "position": 0, "track": 0}
// reset was called, removing the original track so the track has changed
LOG  #2 -  {"position": 0, "track": 0}
// you added some number of tracks to the queue again, so the track has changed
LOG #3 -  {"nextTrack": 0, "position": 0}
```

Some problems that I see with it are:

- `LOG #2` it doesn't entirely make sense to have this payload since there are no tracks, and thus there is no track at position 0.
- `LOG #3` I'm not sure why this event doesn't contain a `track` property, that looks like a bug.

All in all, we realize that there are problems with this particular event, which is why there's a feature on the v4 roadmap to do some deeper thinking about it https://github.com/doublesymmetry/react-native-track-player/issues/1293. With that said, changing things too much at this point is tricky as it can easily introduce breaking changes for folks (thus the v4 schedule). If you find something where the behavior between the platforms is different, or if its clearly a bug that can be addressed without a breaking change we can try to address it in v3.

**Comment by jspizziri** [comment]
I'll close this question for now, if there's something specific you want to address based on my feedback let me know.

**Comment by bradleyflood** [comment]
Thanks @jspizziri
