### ISSUE TITLE
[Feature Request] Support for Video

### ISSUE THREAD

**Issue by tsheaff** [doublesymmetry/react-native-track-player#1792]
**What is the need and use case of this feature?**
Support video playback, rather than just audio playback

**Describe the ideal solution**
Keep the APIs between audio and video playback extremely similar, e.g. only adding properties like aspect ratio but otherwise keeping things the same

**Describe alternatives you've considered**
* Spinning this myself, which is non-trivial and feels more difficult and less "community oriented" than adding Video into this package.
* Using [`expo-av`](https://docs.expo.dev/versions/latest/sdk/av/) or a similar lower-level library, but this does not support background playback, media controls etc. the way this package does. This would also create complexity for apps that want to use this project for Audio but need to switch to e.g. `expo-av` for video, creating wildly divergent APIs
* Use a combo of `expo-av` and [`react-native-music-control`](https://github.com/tanguyantoine/react-native-music-control), which would support video. However, the `react-native-music-control` repo explicitly states that it's deprecated and points users to this project's repo. So this is unmaintained and therefore brittle to OS breaking changes to these APIs.

**Additional context**
I'm not an expert on this library's underlying codebase, I've just skimmed through it at a high level. Therefore, I'm not well-equipped to scope the amount of work here or decide which parts would be the most tricky. There could be scope creep and this could be non-trivial, for example supporting device rotation, screen mirroring, Smart TV integration etc etc.

**How I can Help**
I'm very open to helping assist. Tho as stated, I'm not equipped to lead the implementation here without support from others who know this library's codebase more deeply and can help guide me in the right direction. I'm open to pair-programming on this with others. I also only have an iOS device myself, so I'm stuck to testing Android features on the emulator for now.

**Comment by doug-shontz** [comment]
Yes, this is something that's missing in the Expo community.  I recently did a project where we just had to "live with the limitations" because I spent almost two weeks of a client's time and money trying to find the "right combination" of things to support video background playback.  I tried a bunch of combinations.  The best thing I found was "handing the audio" from the video player off to this package, but that proved to be VERY brittle and always ended up with annoying gaps in playback.

This would be an excellent feature if it could get some traction.  Here is the original conversation that both I and @tsheaff participated in:

[https://expo.canny.io/feature-requests/p/audio-playback-in-background](url)

**Comment by tsheaff** [comment]
@dcvz @mpivchev @jspizziri I'm open to pair programming / divide-and-conquering this with you and the team. How do you typically manage larger diffs like this?

My sense is most of the diff here is in the native layer, and that the TS interfaces can stay quite consistent, with perhaps just a few new methods and a few new options.

Would love to work on design and scoping with y'all.

**Comment by jspizziri** [comment]
@tsheaff @doug-shontz ,

I think this would be a fairly massive amount of work and would require some fundamental changes to the underlying libraries ([SwiftAudioEx](https://github.com/doublesymmetry/SwiftAudioEx) & [KotlinAudio](https://github.com/doublesymmetry/KotlinAudio)). It's effectively an attempt to combine `react-native-video` and RNTP into a single library.

I'd recommend looking at [react-native-video](https://github.com/react-native-video/react-native-video/blob/master/API.md)'s API to see everything that's involved even at that level. Even things like supporting Video DRM providers would be non-trivial. Ultimately, I'm left wondering, why not just use [react-native-video](https://github.com/react-native-video/react-native-video/blob/master/API.md)? It's already a mature video player with its own community and maintainers.

**Comment by CastFX** [comment]
I am facing the same problem: I have a list of videos to play, I want a notification to control the playback.
Currently using react-native-music-control + react-native-video, glued together with redux. But it's currently filled with bugs and tends to desync fairly easily.
Is there a way to use this library manually? I.e. updating manually the progress, without an mp3 file?

**Comment by voquangtin1997** [comment]
I have the same problem @CastFX . can anyone help me?

**Comment by AlirezaHadjar** [comment]
Facing the same exact issue. @jspizziri we want to use `react-native-video` combined with `rntp` in order to update the OS music control. The only job of `react-native-music-control` was to do what I explained. But since it's not maintained, I'm wondering if is there any way to manually update the music control (progress, play/pause state) to couple it with `react-native-video`
