### ISSUE TITLE
Play stopped after disconnected from bluetooth headset instead of paused

### ISSUE THREAD

**Issue by Vietvantue** [doublesymmetry/react-native-track-player#1822]
**Describe the Bug**
When the app disconnected from PBH-200 bluetooth headset, the player state is stopped instead paused.

**Steps To Reproduce**
How can someone else reproduce this bug?
1. Connect the device to PBH-200
2. Play a track
3. Disconnect from the bluetooth headset by press on the power button of the bluetooth headset
4. The player get stopped instead paused.

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.
Follow example code

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?
Yes

**Environment Info:**
react-native: 0.69.4
react-native-track-player:3.2.0
Platform: Android 11
Device:  Galaxy Tab A8

**Comment by kaioduarte** [comment]
I didn't manage to reproduce this behavior with the example app and Galaxy Buds2 Pro.

**Environment Info**:
react-native: 0.68.1
react-native-track-player: 3.2.0
Platform: Android 12
Device: Xiaomi Redmi Note 9S

https://user-images.githubusercontent.com/11046907/213159793-1fe38a97-d002-4afd-b677-099310972458.mov

**Comment by mitchdowney** [comment]
We received a report of a bug in our app that sounds like it might be related to this.

> The problem occurs regardless of the podcast I'm listening to...As soon as the Bluetooth audio device is turned off, the playing podcast immediately disappears from the "playing now" area on the bottom. The app always becomes unresponsive and must be restarted...It happens literally every time (not an exaggeration) and it happens when listening to any of my three bluetooth audio devices. The problem persisted through multiple full uninstalls.

Unfortunately I am unable to reproduce the issue using a Google Pixel 4a, Android 13, RNTP 3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45, with these [Jxrew J51 headphones](https://www.amazon.com/gp/product/B09TN4MP6V/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).

Anyone have ideas for what could cause differences in bluetooth behaviors on Android?

**Comment by puckey** [comment]
@mitchdowney do you have more information about their setup?

**Comment by mitchdowney** [comment]
@puckey I have a little more info but I'm not sure it is helpful. They're using Podverse which has the last 3.2.0 nightly build.

> This occurs on multiple Bluetooth devices (Bose ear buds, 2015 Toyota). It always occurs and is reproducible. This is a new problem started after I applied the most recent Feb Android 13 update

**Comment by mitchdowney** [comment]
@puckey sorry I missed that. The device is a Pixel 7.

**Comment by puckey** [comment]
I am unable to replicate this issue on the nightly example app using a Pixel 6a running the latest update of Android 13 in combination with a pair of Primo Touch bluetooth headphones... When I disconnect the headphones by putting them in their case, the audio pauses and the app continues to function as usual.

**Comment by mitchdowney** [comment]
@puckey I understand as long as this is not reproducible, that it is unlikely we can fix the issue. In any case, the person who reported the issue in Podverse provided more specific device and scenario info:

> I have discovered that the app doesn't crash like this for all bluetooth devices. I have 3 bluetooth devices that reliably cause the app to crash, but I experienced no problems when I connected the Android via bluetooth to a new Genesis brand car. So it appears to me to be only related to the bluetooth device, which explains why it is difficult for you to recreate.
The bluetooth devices that fail for me are (1) 2015 Toyota (2) Bose Quietcomfort earbuds (3) UE Megaboom speaker. All of these devices are somewhat old. I originally had no problems with Podverse using all these devices. I believe it must be related to the Feb 2023 Android update as well. I noticed the Podverse problem immediately after I installed that update on my Pixel 7 (my phone has automatically applied another Android update since Feb). I assumed the Android update broke something and there would be a compatibility patch forthcoming so I waited to report the problem I had with Podverse.
Anyway, all those words is to say that If you want to reproduce the problem, I suggest you look for older (~5 years old) bluetooth devices that you can test with.

Not sure that can help...are there older bluetooth protocols that need separate support? I really don't know the first thing of how bluetooth connectivity works.

**Comment by jspizziri** [comment]
@mitchdowney if you want to move the issue along further, I'd suggest you invest the time in trying to reproduce based on the suggestions that user outlined.

**Comment by SteveWaterfall** [comment]
Hi is this issue still present for anyone else? I have a user for whom it fails regularly when they disconnect their in car bluetooth (app unresponsive and needs a restart), but for other bluetooth devices is fine. Very baffling issue
