### ISSUE TITLE
Cannot apply OTA updates with expo-updates when using track player.

### ISSUE THREAD

**Issue by smontlouis** [doublesymmetry/react-native-track-player#1936]
**Describe the Bug**
When having the track player initialized, the app is not entirely killed when you quit it (I believe so).
The new bundle is never installed because the app is never truly rebooted.

In order for the app to be updated, I need to either: 
- reset the track player with TrackPlayer.reset() before leaving the app
- force stop the app in the app info settings

**Steps To Reproduce**
- initialize the track player
- deploy new OTA update
- reboot the app

**Environment Info:**
react-native-track-player@nightly
React-native bare app with expo-updates for OTA updates.
Android device: Samsung Galaxy S10 android 11
Emulator: Nexus 5X android 13

What OS are you running? OSX

**Comment by smontlouis** [comment]
Might be related to #1927 ?

**Comment by smontlouis** [comment]
Nevermind, I was missing `appKilledPlaybackBehavior`.
I didn't know the default behaviour was `ContinuePlayback`

**Comment by AASHIK-2512** [comment]
I have my music app in that i want to add ota feature , for that i used, react-native-ota-update library, i am getting bundles and bundles are updated new ui is shown ota is working fine.

but the problem is, when any song is playing i am getting remote player but can't perform actions through that player, next prev , seekto play pause not working.

Why and how to? Can you help me with it.
