### ISSUE TITLE
Track Object typescript

### ISSUE THREAD

**Issue by Pnlvfx** [doublesymmetry/react-native-track-player#2017]
Ithink could be a cool feature to add a custom Track Object, without overriding the required parameters but with better Typescript support, actually I see that the Track type has [String: any] at the and and this prevent typescript to find possible undefined values.

I don't know if it's possible to implement this, I just want to share this idea to see if anyone else have the same problem.

**Comment by rmbusch** [comment]
Seconding. My track objects need to hold more than just the default data. I end up storing that data in a corresponding data structure alongside the TrackPlayer but it's not an optimal solution because I have to ensure the state of both data structures stays synced (eg, after the user changes the queue order, etc.)

**Comment by jspizziri** [comment]
@Pnlvfx you can simply extend the `Track` interface with your own and use that in your app. In event listeners you'll simply need to specifically type things that pass around the Track object instead of relying on inference. In theory it would be possible to allow Generics in our typescript code. If someone wants to submit a PR for that I'd be happy to review, but as this stands I'm going to close this.

**Comment by Pnlvfx** [comment]
Yeash jspizziri, that's what I've already does, the only drawback is on the event listener, and the solution was the one you provided. Thanks, if you read I want to ask you another question, for some compatibility with the server I need to pass an album object to the track, but in the Track interface album is declared as a string, could I override it? I mean is the album used internally on the TrackPlayer? I know I can read the source by myself but I also know that there are some native codes which I'm not able to decode, so actually I'm looping on the server tracks and edit them before adding to the TrackPlayer

**Comment by jspizziri** [comment]
Yes, it needs to be a string.

**Comment by Pnlvfx** [comment]
wrap the whole package into a new trackPlayer object and return it using your type, I did it when i needed, as suggested by the author too, the only hooks that you can't wrap are the event listeners

**Comment by esorinas** [comment]
Thanks for your suggestion, that will surely do the trick! It will definitely be cleaner than my `as`-approach, although I hope we get a less ad-hoc support for this at some point in the future :)
