### ISSUE TITLE
Ability to remove event listeners + Expo Support

### ISSUE THREAD

**Issue by objectiveSee** [doublesymmetry/react-native-track-player#2019]
**What is the need and use case of this feature?**
There is an API for adding a event listeners, but there's not one for removing it. I have been able to figure out how to get this module working inside of an expo app, however, there are still a few issues that I am trying to get around. Specifically using `registerPlaybackService` is throwing exceptions for me about an undefined type or something. In reality this code isn't even needed. The better solution would be to have a react component add an event listener when it needs it, and then to remove the listener when that component is destroyed. This is classic object lifestyle. This would also remove the need from having a call back handler that is not tied to any component, and therefore will never be deallocated. It would probably fix some of the issues about hot reloads with React Native too.

**Describe the ideal solution**
Modify, the library is that there is a remove event listener function.

**Describe alternatives you've considered**
Right now I'm trying to figure out some hacky things like using global variables to keep track of that listeners.

**Additional context**

The following code will throw an error, undefined is not a function. The error happens, even if I come in and out the entire contents of the PlaybackService function. Perhaps a better solution is just to get rid of `registerPlaybackService` all together. 🤔 

I also noticed that I can get things working with expo by just calling the playback service function manually after the track player has been successfully set up (but not using registerPlaybackService). 

```
// App.tsx
import { PlaybackService } from './src/services/trackPlayerService';

// Setup for the react native track player
// https://react-native-track-player.js.org/docs/basics/getting-started
TrackPlayer.registerPlaybackService(() => require('./src/services/trackPlayerService') );
```

```
// trackPlayerService.ts

import TrackPlayer, { Event} from "react-native-track-player";
export async function PlaybackService() {
    TrackPlayer.addEventListener(Event.PlaybackError, (error) => {
        console.log("PlaybackError");
        console.log(error);
    });
    TrackPlayer.addEventListener(Event.PlaybackTrackChanged, (track) => {
        console.log("PlaybackTrackChanged");
        console.log(track);
    });
}
```

**How I can Help**
I'm not familiar with the code base enough to jump in there. If somebody wanted appointment in the right direction that I might be able to make a fix. It seems like this is a relatively straightforward thing because EventEmitter is being used. 

I'm also willing to write up more documentation on how to get things running with Expo

**Comment by bradleyflood** [comment]
Hey @objectiveSee :)

Expo is supported - See https://react-native-track-player.js.org/docs/next/basics/installation#expo

There's actually a few reasons why the background playback service has to be registered OUTSIDE of the React lifecycle. Primarily because when the app is in the background your React root may be unmounted by React Native or by the OS - and this would cause your music playing to stop. So the background playback service can't be within React.

Thank you

**Comment by hirbod** [comment]
@bradleyflood, sorry for commenting on a closed issue, but there's one issue for which I haven't found a solution: hot reload (when pressing the R button). This essentially reboots everything, but I end up having multiple events registered in that instance.

This isn't exclusive to a dev scenario, because hot code push (OTA with expo-updates) also triggers a `.reloadAsync`, which is technically identical. I need to ensure that a second `registerPlaybackService` doesn't register all the events again. Currently, there's no way for me to call EmitterSubscription's `.remove()`.

Is there a known solution to this?

**Comment by objectiveSee** [comment]
I've had the same problem. It only is an issue when I change code related to this library. When I am just changing my normal react code and there's no issue. It's annoying, but at least it is something you can work around.

**Comment by hirbod** [comment]
Yes, the issue only happens when the whole runtime gets destroyed and reloaded (e.g. pressing R or triggering expo-updates reloadAsync())

Trying to figure out a way to call .remove() before that happens.

**Comment by RomanTsegelskyi** [comment]
Expo installation link is broken (https://react-native-track-player.js.org/docs/next/basics/installation#expo), are there updated docs?
