### ISSUE TITLE
Add track object to PlaybackProgressUpdatedEvent

### ISSUE THREAD

**Issue by curthipster** [doublesymmetry/react-native-track-player#2022]
**What is the need and use case of this feature?**
When subscribing to the `PlaybackProgressUpdated` event, I need to use the info stored with the track. The `PlaybackProgressUpdatedEvent` includes the `track`, which is the index, but it does not have a reference to the Track object.

**Describe the ideal solution**
The new event `PlaybackActiveTrackChanged` includes the Track objects on the event itself, which is a nice improvement to the API. Also, the semantics are more intuitive, wherein `track` refers to the object and `index` refers to the index.

A backwards compatible change would add the Track object to the existing event, but it would mean the semantics are inconsistent across event types. Alternatively, a new event name and type would be non-breaking.

**Describe alternatives you've considered**
It's easy enough to workaround in the code by making an async call to `getQueue` in my event handler. I prefer the ergonomics of the newer event.

**Additional context**
This is similar to #2011.

**How I can Help**
I'm happy to help test.

**Comment by puckey** [comment]
Since `PlaybackProgressUpdatedEvent` can be emitted very often, I am not sure serializing the whole track object is ideal here.. I would suhhest using the [useTrackPlayerEvents](https://react-native-track-player.js.org/docs/next/api/hooks#usetrackplayerevents) hook to subscribe to both `PlaybackProgressUpdatedEvent` and `PlaybackActiveTrackChanged `

**Comment by puckey** [comment]
@curthipster I would expect it to be, but please let us know if it is not
