### ISSUE TITLE
V4 crashes hourly, far more than beta

### ISSUE THREAD

**Issue by fivecar** [doublesymmetry/react-native-track-player#2251]
**Describe the Bug**
When playing tracks, and sometimes when switching tracks, the current non-beta crashes frequently on iOS. 

**Steps To Reproduce**
This happens regularly - and I have App Store logs to show this. It does so far more than the final beta, which I ran in production for over 6 months. It happens randomly -- perhaps once an hour -- often mid-playback, so it's a bit hard to exactly reproduce on demand. 

**How I can Help**
More than happy to help if the cause of this is known. What's particularly unclear to me is what changed between beta and now that could have it crashing so much more frequently.

**Comment by jspizziri** [comment]
@fivecar this issue needs more information to have any progress made toward a solution. At the very least, crash logs, and ideally a reproduction. It'd also recommend that you verify that nothing else about your app has changed since the beta and that the only variable in the equation would be RNTP.

**Comment by fivecar** [comment]
Agreed completely @jspizziri. I'm going to focus on getting some crash logs and reopening this with more constructive info.
