### ISSUE TITLE
[Documentation] v4 Docs remove() references tracks instead of indices

### ISSUE THREAD

**Issue by uzegonemad** [doublesymmetry/react-native-track-player#2262]
The docs [currently state](https://github.com/doublesymmetry/react-native-track-player/blob/6e2f30c934fb126dc7b89fd929316b4f2019121c/docs/docs/api/functions/queue.md#L21) that the `remove()` method expects a Track(s). It actually expects an index/indices, and passing tracks will crash the app (at least on iOS).

**Note:** I haven't confirmed if any other methods in the docs are also outdated.

**Comment by krestaino** [comment]
I can confirm the same on Android. I didn't know if it was a bug or simply the docs needed to be updated, but since it's like this on iOS and [this looks like code for Android](https://github.com/doublesymmetry/react-native-track-player/blob/db86df1a6c6a2c1e5af0da3d94b35c4c4120b162/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt#L310-L331), I'm assuming the docs just need to be updated.
