### ISSUE TITLE
Duplicate actions in notification controller on Android 13+

### ISSUE THREAD

**Issue by ouabing** [doublesymmetry/react-native-track-player#2321]
**Describe the Bug**
I've got reports from my users who uses ColorOS 13+(which is the default system on some OnePlus and Oppo devices), they found  duplicate rewind and ff actions in notification controller. After digging for a while, I found KotlinAudio will add custom actions for rewind, ff and stop actions on Android 13+ aligning with [the official behavior change](https://developer.android.com/about/versions/13/behavior-changes-13?hl=zh-cn#playback-controls), it still attempt to add these actions to ExoPlayer, which may result in duplicate actions on some custom Android system.

I have already create a [PR](https://github.com/doublesymmetry/KotlinAudio/pull/107) to solve this issue, I'm posting this bug report here to see if there are any scenerios I might have missed.

![20240531-144645](https://github.com/doublesymmetry/react-native-track-player/assets/1430376/dc157698-8234-48f7-9681-75e09828180a)

**Steps To Reproduce**
Add `Capability.JumpForward`, `Capability.JumpBackward` or `Capability.Stop` to capabilities when invoking `updateOptions`

**Code To Reproduce**
```
Playback.updateOptions({
  forwardJumpInterval: 15,
  capabilities: [
    Capability.Play,
    Capability.JumpForward,
    Capability.JumpBackward
  ]
})
```

**Replicable on Example App?**
Yes

**Environment Info:**
Paste the results of `npx react-native info`
0.73.8
Paste the exact `react-native-track-player` version you are using
4.1.1
Real device? Or simulator?
OnePlus Ace3
What OS are you running?
ColorOS 14(Based on Android 14)

**How I can Help**
See [PR](https://github.com/doublesymmetry/KotlinAudio/pull/107)

**Comment by lovegaoshi** [comment]
thanks for the PR!

do u know if these specific OS providers map bluetooth events to forward/rewind as well when forward/rewind is enabled? like KeyEvent.KEYCODE_MEDIA_FAST_FORWARD (https://github.com/lovegaoshi/KotlinAudio/commit/a8990b57ae6cff0d85f9139d20d725ffbe224ed8). I wonder if for these OSes its better to use the native forward/rewind mapping instead of via custom actions.
unrelated, the whole customaction system needs to be overhauled at some point.
