### ISSUE TITLE
[administrative] maintenance status

### ISSUE THREAD

**Issue by lovegaoshi** [doublesymmetry/react-native-track-player#2340]
hi!

this is a maintenance status request to the lib collaborators/maintenance team @dcvz @jspizziri @puckey. RNTP hasnt seen a major maintenance effort in a couple of months. I'm currently following the new arch fix for RNTP and a bunch of other libraries related to HeadlessJsTask (https://github.com/facebook/react-native/issues/44255) and the fb team expressed a similar concern that this lib is not maintained. I understand everyone is busy and I still see myself being active in the RN community since my app using RNTP is actively maintained, so Im volunteering to maintain the android part of RNTP to make the library alive and give fb some confidence to not deprecate HeadlessJs, if necessary. I've worked on some bug fixes and the android auto FR, fade effect FR and crossfade FR here. thanks!

**Comment by jspizziri** [comment]
Hi @lovegaoshi ,

I use this library in production and I'm pretty sure @puckey does too. Regarding a lack of maintenance effort over the last couple of months: largely I'd say this is due (at least from my perspective) to things being pretty stable. I've got some work on the back burner regarding better web support, but it hasn't been critical for me to get across the finish line.

I've been keeping an eye on your work and am very grateful for all the energy and effort you've put into the library! Regarding wanting to help maintain the android side, I'd say all of us would be super on board with contributions. I think most of your work has been on Android auto to this point and, as a result not much has been merged due to reasons we've already chatted about on other issues (largely the hard fork of HeadlessJS).

At a high-level here are my thoughts on contribution:

1. Bug fixes for Android are super welcome. I've we haven't been on the ball with that I apologize. Just ping me as to what things have slipped through the cracks and I can work with you on them.
2. Enhancements are an interesting area, as a primary concern is feature parity across all platforms. I realize that you largely only care about Android, but the fundamental nature of RNTP is a cross-platform and consistent experience (as much as that's possible. That said, while all the features you mentioned are super interesting, having a serious discussion about them in an "Android Only" context is a hard sell (at least for me).

Regarding keeping this library alive. I certainly intend to keep it alive as much as I'm able given that I'm currently using it in several production deployments.

Does that help at all or answer your questions?

**Comment by lovegaoshi** [comment]
appreicate the fast response, I hope this is enough for fb to consider resolving the new arch headlessJs issue on a priority. in the meantime if I can draw attention to this PR from the expo team (https://github.com/doublesymmetry/react-native-track-player/pull/2290) it is very appreciated. thank you for the work as always.
