### ISSUE TITLE
Compatibility with react-native-video

### ISSUE THREAD

**Issue by miltonzarmada** [doublesymmetry/react-native-track-player#2405]
Tried implementing this library to get meta controls on Lock Screen but failed. Does this library work for video files or just audio files. Thank you. 😃

**Comment by lovegaoshi** [comment]
pls fill out the issue template instead of ignoring it??? "but failed" says practically nothing?? although:

1. can someone use rntp and RNV in the same repo - yes cuz i do [this](https://github.com/lovegaoshi/azusa-player-mobile/blob/1bdb8b556f4acf615d3a76c6fb932cb31c97196f/package.json#L117)
2. can someone use rntp to control RNV - thats a terrible idea cuz rnv or expo-video now [supports it by itself](https://github.com/TheWidlarzGroup/react-native-video/pull/3723)

**Comment by jspizziri** [comment]
I'm going to close this due to a lack of response. In short, this library is exclusively audio.
