### ISSUE TITLE
[Feature] Different Jump Intervals

### ISSUE THREAD

**Issue by Pczek** [DoubleSymmetry/react-native-track-player#378]
How about to implement two options for the jump interval in order to be able to have two different values?
`jumpIntervalForward` & `jumpIntervalBackward`.
`skipInterval` & `rewindInterval`?

I've seen some podcasts app setting different intervals for skip and rewind. It can be quite useful.

+45 Seconds and -10 seconds for example. Skipping fast forward but only slowly back.

**Comment by nishanBende** [comment]
@Guichaguri I have added this enhancement in my fork. Can I generate PR?

**Comment by Guichaguri** [comment]
Yes, please!

**Comment by feedcast-me** [comment]
@nishanBende do you have this feature published somewhere?

**Comment by nishanBende** [comment]
@feedcast-me since I implemented it, I was facing an issue in my iOS app in production, notification control button used to get disabled after multiple calls to updateOptions. So, I am not using it. 
Sorry, but I'll try to get a proper solution and reply here.
The functionality itself is very simple just passing parameters makes it work, but the button disabled issue I guess is related to this.
https://github.com/react-native-kit/react-native-track-player/issues/775

**Comment by dcvz** [comment]
This has now been added in: https://github.com/DoubleSymmetry/react-native-track-player/pull/1177
