### ISSUE TITLE
State for Ending a track

### ISSUE THREAD

**Issue by ithustle** [DoubleSymmetry/react-native-track-player#472]
Why the playback-state return `paused` when a song finish? Perhaps should be something like `finish`? 

For now, I'm using `playback-queue-ended` event to check whether song is finished.

Is there another or specific way to know when a song finish?

**Comment by moneynguyen0o0** [comment]
+1

**Comment by mitchdowney** [comment]
I need to detect when a track has reached the end of its duration so I can automatically delete its file locally. I don't think playback-track-changed or playback-queue-ended will work because they happen whenever the track changes, not just when the end of the file is reached.

Is there a way to detect with react-native-track-player when a track has ended? Or a workaround you can think of?

**Comment by Pandan** [comment]
+1

**Comment by TonyGao625** [comment]
+1

**Comment by curiousdustin** [comment]
Related: https://github.com/react-native-kit/react-native-track-player/issues/916, https://github.com/react-native-kit/react-native-track-player/issues/918

**Comment by davidcort** [comment]
I am using useTrackPlayerEvents. When a track finished, the state is "paused", this should be "stopped". 
I tried with remote-stop because i am making a podcast player but not works :(

**Comment by Guichaguri** [comment]
Also related: #942

**Comment by mitchdowney** [comment]
@dcvz do you know if an event for "track has played all the way until the end" will be included in RNTP 2.0? As you can see above we have a few features this would unblock us on with Podverse.

**Comment by colecanning** [comment]
It's a shame this was marked as completed as there is still no solution, no event for when a song finishes playing
