### ISSUE TITLE
iOS cannot play base64 url

### ISSUE THREAD

**Issue by tungmt** [DoubleSymmetry/react-native-track-player#767]
I tried to add and play base64 audio. I set base64 audio as url with prefix 'data:audio/wav;base64,' . It can play well on android but some how it not work on ios. With the same config I set url as https audio url then it work well.

RN v0.60.5
react-native-track-player v1.1.8

**Comment by Guichaguri** [comment]
This is those kind of features that we don't know if we'd like to support officially. The scope of the project is to provide an audio solution for music/podcast apps that play more than 30 seconds of audio. The reason is that the module is built around providing a smooth streaming experience by the cost of using more resources than a simple audio player.

Encoding audio in base64 is only useful for short audio files such as sound effects, which are out of the project's scope. I recommend using `react-native-sound` for that.

If you're not using it for short audio files, we highly recommend that you store the audio into a file as it would stream it instead of fully buffering the file.

**Comment by mama00** [comment]
I need to play a base64 music encrypted.Im decrypting it chunk by chunk they best option would have been to pass each decrypted chunk to the player also but I cant isn't it too slow to decrypt all in a mp3 format and after load it. I will also have to delete the decrypted so that no one can acess it except the App

**Comment by mikaoelitiana** [comment]
@mama00 I am working on something similar, have you found a workaround?

**Comment by tungmt** [comment]
@mikaoelitiana play base64 audio use react-native sound and react-native-music-control will be workaround solution

**Comment by mikaoelitiana** [comment]
hi @tungmt, I will try that, thanks
