### ISSUE TITLE
[ios] Lock screen controls remain after last track ends. (NowPlayingInfoCenter)

### ISSUE THREAD

**Issue by curiousdustin** [DoubleSymmetry/react-native-track-player#825]
On iOS, the lock screen controls should disappear after the last track ends. 

Instead, they remain visible.

**Comment by curiousdustin** [comment]
I tried adding the following to `RNTrackPlayer.swift` inside `player.event.playbackEnd.addListener`

```
self.player.nowPlayingInfoController.clear()    
```

As suggested here: https://github.com/jorgenhenrichsen/SwiftAudio/issues/83

However, this clears out the info but the controls remain in place.

**Comment by Thomas0c** [comment]
Have been looking at a similar issue and setting `nowPlayingInfo` to an empty dictionary seems to do the trick: `MPNowPlayingInfoCenter.default().nowPlayingInfo = [:]`.

**Comment by curiousdustin** [comment]
Are you finding that your suggestion works differently than `self.player.nowPlayingInfoController.clear()`? Where did you put that line?

**Comment by Thomas0c** [comment]
Yes. It actually clears the audio player including the controls.
Currently calling it in the `reset` function in `RNTrackPlayer.swift` within the `DispatchQueue.main.async` block.

**Comment by curiousdustin** [comment]
@Thomas0c do the lock screen control disappear if you are watching them when the queue ends?

For me everything works as expected, UNLESS I have the lock screen controls visible when the queue ends. In this case, using either `MPNowPlayingInfoCenter.default().nowPlayingInfo = [:]` or `self.player.nowPlayingInfoController.clear()` causes the controls to reset to a "default" state. (see attached)

![lock-screen](https://user-images.githubusercontent.com/1706540/72176829-8c4d1c80-339c-11ea-9e9a-40c282f03484.jpeg)

At this point, if I turn the screen off and back on, the controls go away as they should.

**Comment by raultunduc** [comment]
Did someone solve this issue? Is this issue still in tracking?

**Comment by waheedakhtar694** [comment]
Any update on this?

**Comment by waheedakhtar694** [comment]
Here is the `destroy` method which only prints a message in the log

```
@objc(destroy)
    public func destroy() {
        print("Destroying player")
    }
```

**Comment by waheedakhtar694** [comment]
This is not a perfect solution but i found a workaround that updating the options after restting the player works for me.

```
    await RNTrackPlayer.reset()
    await RNTrackPlayer.updateOptions({ stopWithApp: true,
      capabilities: [
        Capability.Play,
        Capability.Stop,
        Capability.SkipToNext,
        Capability.SkipToPrevious,
        Capability.Pause
      ]})await RNTrackPlayer.reset()
      ```

**Comment by timboudreau** [comment]
Not a react native user, but I ran across this while searching for info on an update bug in iOS 26, and I am the author of an iOS audio player, so a few hard-won tips on how to make this sort of thing work in case they are useful:

 * If you are using AVAudioPlayer or friends, and scheduled an audio file or buffer to play, the player object iOS provides will simply continue playing silence past the end of the buffer/file, updating its `AVAudioTime` buffer position to past the end of it - that's just how it works
 * If you want to actually detect when playback logically ended (you've played at least as many samples as you scheduled), you have to provide a callback when you initiate playback.  There is some caveats to that, however:
   * The buffer having been completely played is *not the only reason* you might get that callback - it can also happen if audio playback is interrupted (user, say, connected audio to their car or disconnected it, or a call arrived) and may or may not happen if the player is programmatically stopped.  So you *absolutely cannot trust* that the reason you got a callback is because playback completed. You need to check the playback position from the audio engine (remembering, if you started playback part way through *but not if you un-paused* to add the seek position where you started playback to the `AVAudioTime` the player reports.
   *  You get your callback when the last buffer of audio is *flushed to the playback hardware*. That is **not the same as when that audio has been played** - depending on the os's scheduler, you will sometimes get a callback, and if you check the position of the player - which is the position at which the hardware is *within the output buffer + previous buffer lengths*, you will find the `position` < `total samples to play` - it looks like you are not done, but you actually are (if you implement playlist functionality, as I did, and use this is the trigger to play the next song, and assume not done actually means not done, your playlists will break - randomly and rarely, but they will).
   * What you need to do about it: When you get the callback, compute the number of sample-frames that have been played as described above.  If the number is less than the number of samples you expected to play, then get the buffer size from the `AVAudioSession` (do not cache it, it will change when the device connects or disconnects - buffer size is it's whole own can of worms - small buffer sizes offer better responsiveness, but too small and CarPlay silently breaks). If `framesYouExpectedToPlay - framesActuallyPlayed < bufferSize` then you **are** at the end.

If I had it all to do again, I would do playback with AudioUnits and Core Audio and avoid as much of the layers of developer-friendly, buggy,  catch-NSExceptions-in-objective-c-or-die, race-condition-prone goo Apple layered over them as possible.

Hope this helps someone.
